### ISSUE TITLE
Unsupervised llamas dataset

### ISSUE THREAD

**Issue by karstenBehrendt** [amusi/awesome-lane-detection#4]
I released a new dataset on lane marker detection and segmentation, the Unsupervised LLAMAS dataset at [https://unsupervised-llamas.com/](https://unsupervised-llamas.com/). It comes with code at [https://github.com/karstenBehrendt/unsupervised_llamas](https://github.com/karstenBehrendt/unsupervised_llamas)

I would really like to add it to your collection. Let me know if I should create a PR to do so or just close this issue if it does not interest you.

**Comment by amusi** [comment]
Thank you. I have added the dataset to this project.
