### ISSUE TITLE
VPGNet dataset

### ISSUE THREAD

**Issue by SeokjuLee** [amusi/awesome-lane-detection#8]
[VPGNet](https://arxiv.org/abs/1710.06288) dataset is available.
It contains around 21K images with human-annotated lane, road markings, and vanishing point labels.
For more details, please check our project [page](https://github.com/SeokjuLee/VPGNet#vpgnet-dataset).

**Comment by amusi** [comment]
Ok, I have added it to the project.
Thanks.
